name: calimiro_app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  permission_handler: ^11.3.1
  tflite_flutter: ^0.11.0
  google_mlkit_pose_detection: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/pose_classifier.tflite
